CREATE TABLE  TB_FUNC (
MATRICULA INT PRIMARY KEY IDENTITY,
NOME VARCHAR (255) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
SALARIO MONEY NULL,
DATAADMISSAO DATE DEFAULT (GETDATE()),
DATADEMISSAO DATE NULL,
INICIOFERIAS DATE NULL,
FIMFERIAS DATE NULL,
STATUS_FUNC VARCHAR (20) CHECK (STATUS_FUNC IN ('ATIVO','INATIVO','FERIAS','LICENÇA','INSS')),
CODDEPTO INT)



INSERT INTO TB_FUNC (NOME, DATANASCIMENTO,SALARIO,DATAADMISSAO,DATADEMISSAO,INICIOFERIAS,FIMFERIAS, STATUS_FUNC, CODDEPTO)
VALUES ('ANA MARIA', '2000-01-01', 1200.55, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 1),
('JOSE HENRIQUE', '1998-11-20', 2575.55, '2005-09-01','2017-12-01',NULL,NULL, 'INATIVO', 7),
('ANA MARIA', '2002-08-21', 950.00, '2019-01-01',NULL,NULL,NULL, 'ATIVO', 6),
('LUAN FELIX', '1991-09-28', 3500.00, '2013-04-01',NULL,NULL,NULL, 'ATIVO', 1),
('FELIPE JOSE DOS SANTOS', '1996-01-11', 4000, '2011-05-01','2015-01-29',NULL,NULL, 'INATIVO', 2),
('MARCELO JOSE', '1980-10-05', 7000, '2000-05-01',NULL,'2019-05-01','2019-06-01', 'ATIVO', 2),
('MARIANA MARIA', '1987-02-08', 4500, '2010-01-01',NULL,NULL,NULL, 'INSS', 3),
('JULIANA MARIA DOS SANTOS', '2002-01-01', 2000, '2017-05-01',NULL,NULL,NULL, 'LICENÇA', 5),
('MARIA ALICIA', '2001-01-01', 950, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 4)
	
INSERT INTO TB_FUNC (NOME, DATANASCIMENTO,SALARIO,STATUS_FUNC, CODDEPTO)
VALUES ('MARIA ALICIA', '2003-09-18', 950,  'ATIVO', 3)


/******************* ORDER BY *************************/
SELECT * 
FROM TB_FUNC
ORDER BY NOME


SELECT * 
FROM TB_FUNC 
ORDER BY NOME , SALARIO 



SELECT * 
FROM TB_FUNC 
ORDER BY NOME DESC

SELECT * 
FROM TB_FUNC 
ORDER BY NOME ASC, SALARIO DESC

/****************** OPERADORES LOGICOS *******************//

SELECT  MATRICULA, NOME, DATADEMISSAO , STATUS_FUNC
FROM TB_FUNC
WHERE DATADEMISSAO IS NULL
AND STATUS_FUNC = 'ATIVO'



SELECT  MATRICULA, NOME, DATADEMISSAO , STATUS_FUNC
FROM TB_FUNC
WHERE DATADEMISSAO IS NULL
OR STATUS_FUNC = 'ATIVO'



SELECT 
MATRICULA, NOME, SALARIO, STATUS_FUNC
FROM TB_FUNC
WHERE NOT SALARIO >= 4000

/****************** OPERADORES ARITMETICOS *******************//

SELECT 
NOME, SALARIO,
(SALARIO * 4) / (SALARIO*2) AS CONTA,

SALARIO + 50 AS ADICAO,
SALARIO - 20 AS SUBTRACAO,
SALARIO * 1.20  AS AJUSTE_20_PCENTO,
SALARIO / 2 AS DIVISAO
FROM TB_FUNC
WHERE STATUS_FUNC = 'ATIVO'



/****************** OPERADORES RELACIONAIS *******************//

SELECT * 
FROM TB_FUNC
WHERE STATUS_FUNC = 'ATIVO'


SELECT * 
FROM TB_FUNC
WHERE SALARIO >= 2000


SELECT * 
FROM TB_FUNC
WHERE SALARIO >= 2000 
AND SALARIO <= 4000


SELECT * 
FROM TB_FUNC
WHERE STATUS_FUNC <> 'ATIVO'

SELECT * 
FROM TB_FUNC
WHERE datanascimento > '1992-01-01' --ANO MES DIA
AND datanascimento < '2002-01-01'

/************ OPERADORES AUXILIARES *********/

SELECT * 
FROM TB_FUNC
WHERE DATADEMISSAO IS NULL

SELECT * 
FROM TB_FUNC
WHERE DATADEMISSAO IS NOT NULL


SELECT * 
FROM TB_FUNC
WHERE DATAADMISSAO BETWEEN '2012-01-01' AND '2018-12-20'

SELECT * 
FROM TB_FUNC
WHERE DATADEMISSAO  BETWEEN '2017-01-01' AND '2017-12-20' AND '2017-02-02'




SELECT * 
FROM TB_FUNC
WHERE STATUS_FUNC IN ('ATIVO','FERIAS')

SELECT * 
FROM TB_FUNC
WHERE MONTH(DATAADMISSAO) IN (1,2)

	SELECT * 
FROM TB_FUNC 
WHERE MONTH(DATAADMISSAO)  NOT IN (10,11)




SELECT * 
FROM TB_FUNC
WHERE NOME LIKE 'JOSE'

SELECT * 
FROM TB_FUNC
WHERE NOME LIKE 'JOSE%'

SELECT * 
FROM TB_FUNC
WHERE NOME LIKE '%JOSE'

SELECT * 
FROM TB_FUNC
WHERE NOME LIKE '%JOSE%'


****** EXTRAS ***********


SELECT
F.NOME AS 'NOME FUNCIONÁRIO',
'DATA DE ADMISSÃO' = F.DATAADMISSAO,
F.SALARIO 'SALÁRIO FUNCIONÁRIO'
FROM TB_FUNC AS F


SELECT NOME, STATUS_FUNC,
CASE STATUS_FUNC
	WHEN 'ATIVO' THEN 'A'
	WHEN 'INATIVO' THEN 'I'
	WHEN 'FERIAS' THEN 'F'
ELSE
	'O'
END SIGLA_STATUS
FROM TB_FUNC



SELECT NOME, SALARIO,
CASE 

WHEN SALARIO > 1200 AND SALARIO < 1500 THEN SALARIO * 1.10

WHEN SALARIO > 1501 AND SALARIO < 2000 THEN SALARIO * 1.20

WHEN SALARIO < 1000 THEN SALARIO
END SALARIO_COM_REAJUSTE

FROM TB_FUNC


